#!/bin/sh /etc/rc.common
#
# Copyright (C) 2021 eGloo, Incorporated
#
# This is free software, licensed under the GNU General Public License v2.

START=50
STOP=50

USE_PROCD=1
PROG=/usr/sbin/netify-fwa
PID_FILE=/var/run/netify-fwa/netify-fwa.pid

start_service() {
    mkdir -p /var/run/netify-fwa

    procd_open_instance
    procd_set_param command $PROG -R
    procd_set_param pidfile $PID_FILE
    procd_set_param file /etc/netify-fwa/netify-fwa.json
    procd_set_param respawn
    procd_close_instance
}
