#!/bin/sh

[ -f /opt/rh/rh-python36/enable ] && . /opt/rh/rh-python36/enable

PYTHON="$(which python3 2>/dev/null)"

if [ -z "$PYTHON" ]; then
    PYTHON="$(which python3.6 2>/dev/null)"
fi

if [ -z "$PYTHON" ]; then
    echo "Unable to locate Python3 interpreter."
    exit 1
fi

exec $PYTHON -Es /usr/share/netify-fwa/nfa_main.py $@
