name: building sturdynet image

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: mkdir build && cd build
      - run: wget -v "https://runners-cache-sturdynet.s3.us-west-2.amazonaws.com/rootfs/openwrt-22.03.4-x86-64-generic-rootfs.tar.gz"
      - run: tar -xf openwrt-22.03.4-x86-64-generic-rootfs.tar.gz
      - run: rm -rf openwrt-22.03.4-x86-64-generic-rootfs.tar.gz
      - run: sudo docker builder prune --force --all
      - run: sudo docker system prune --force --all
      - run: sudo docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - run: sudo docker image build --file=Dockerfile --pull --tag=${{ secrets.DOCKERHUB_USERNAME }}/rootfs:latest .
      - run: sudo docker push "${{ secrets.DOCKERHUB_USERNAME }}/rootfs:latest"
      - run: sudo docker logout
      - run: cd .. && rm -rf build
