name: building sturdynet image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: wget -v "https://runners-cache-sturdynet.s3.us-west-2.amazonaws.com/rootfs/openwrt-22.03.4-x86-64-generic-rootfs.tar.gz"
      - run: tar -xf openwrt-22.03.4-x86-64-generic-rootfs.tar.gz
      - run: ls
      - run: rm -rf openwrt-22.03.4-x86-64-generic-rootfs.tar.gz
      # - name: Login to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: sudo docker image build --file=Dockerfile --pull --tag=sturdynetoci/rootfs:v7 .
      - run: sudo docker push "sturdynetoci/rootfs:v7"
      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/rootfs:v7
